//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStore
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using PropertyChanged;

    public partial class PurchaseDetail
    {
        public event PropertyChangedEventHandler PropertyChanged;
        public int PurchaseDetailID { get; set; }
        public Nullable<int> PurchaseDetailPurchase { get; set; }
        public Nullable<int> PurchaseDetailProduct { get; set; }
        public Nullable<int> PurchaseDetailQuantity { get; set; }
        public Nullable<int> PurchaseDetailTotal { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}
